### ISSUE TITLE
移动端首页文章内容溢出

### ISSUE THREAD

**Issue by l2dy** [spiritree/typecho-theme-amaze#1]
<kbd>![spiritree me- iphone 6](https://user-images.githubusercontent.com/14329097/28742126-590e3652-7417-11e7-9b74-a01d8d33f5aa.png)</kbd>

**Comment by spiritree** [comment]
感谢，看了下是amazeUI里的CSS导致溢出
```css
code {
  white-space: no-wrap;
}
```
已修复 清缓存再打开即可
